[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "at_nlp"
version = "0.0.1a"
license = { text = "MIT License" }
requires-python = ">= 3.10"
dependencies = [
    "pydantic",
    "scikit-learn",
    "pandas",
    "numpy",
    "tqdm",
    "dask-expr",
    "pyarrow"
]