name: Build/Push PyPI

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and Publish To PyPI
        uses: JRubics/poetry-publish@v2.0
        with:
          python_version: ${{ vars.PYTHON_VERSION }}
          pypi_token: ${{ secrets.PYPI_TOKEN }}
          repository_username: ${{ secrets.REP_USER }}
          repository_password: ${{ secrets.REP_PASS }}
